/****************************************************************************
 *
 * Cass80 tool - Z80 token (mnemonics) and flags
 *
 * Copyright (C) 2020 Jürgen Buchmüller <pullmoll@t-online.de>
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ****************************************************************************/
#include <QHash>
#include "z80token.h"

z80Token::z80Token(const z80Token& other)
    : m_mnemonic(other.m_mnemonic)
    , m_parameters(other.m_parameters)
{
}

z80Token::Mnemonics z80Token::mnemonic() const
{
    return m_mnemonic;
}

const char* z80Token::parameters() const
{
    return m_parameters;
}

z80Token::z80Token(z80Token::Mnemonics m, const char* p)
    : m_mnemonic(m)
    , m_parameters(p)
{

}

z80Token& z80Token::operator=(const z80Token& other)
{
    m_mnemonic = other.m_mnemonic;
    m_parameters = other.m_parameters;
    return *this;
}

QLatin1String z80Token::string(Mnemonics m)
{
    static const QHash<Mnemonics,QLatin1String> lookup({
	{zADC,	    QLatin1String("ADC")},
	{zADD,	    QLatin1String("ADD")},
	{zAND,	    QLatin1String("AND")},
	{zBIT,	    QLatin1String("BIT")},
	{zCALL,	    QLatin1String("CALL")},
	{zCCF,	    QLatin1String("CCF")},
	{zCP,	    QLatin1String("CP")},
	{zCPD,	    QLatin1String("CPD")},
	{zCPDR,	    QLatin1String("CPDR")},
	{zCPI,	    QLatin1String("CPI")},
	{zCPIR,	    QLatin1String("CPIR")},
	{zCPL,	    QLatin1String("CPL")},
	{zDAA,	    QLatin1String("DAA")},
	{zDB,	    QLatin1String("DB")},
	{zDEC,	    QLatin1String("DEC")},
	{zDEFB,     QLatin1String("DEFB")},
	{zDEFW,     QLatin1String("DEFW")},
	{zDEFD,     QLatin1String("DEFD")},
	{zDEFM,     QLatin1String("DEFM")},
	{zDEFS,     QLatin1String("DEFS")},
	{zDI,	    QLatin1String("DI")},
	{zDJNZ,	    QLatin1String("DJNZ")},
	{zEI,	    QLatin1String("EI")},
	{zEX,	    QLatin1String("EX")},
	{zEXX,	    QLatin1String("EXX")},
	{zHLT,	    QLatin1String("HLT")},
	{zIM,	    QLatin1String("IM")},
	{zIN,	    QLatin1String("IN")},
	{zINC,	    QLatin1String("INC")},
	{zIND,	    QLatin1String("IND")},
	{zINDR,	    QLatin1String("INDR")},
	{zINI,	    QLatin1String("INI")},
	{zINIR,	    QLatin1String("INIR")},
	{zJP,	    QLatin1String("JP")},
	{zJR,	    QLatin1String("JR")},
	{zLD,	    QLatin1String("LD")},
	{zLDD,	    QLatin1String("LDD")},
	{zLDDR,	    QLatin1String("LDDR")},
	{zLDI,	    QLatin1String("LDI")},
	{zLDIR,	    QLatin1String("LDIR")},
	{zNEG,	    QLatin1String("NEG")},
	{zNOP,	    QLatin1String("NOP")},
	{zOR,	    QLatin1String("OR")},
	{zOTDR,	    QLatin1String("OTDR")},
	{zOTIR,	    QLatin1String("OTIR")},
	{zOUT,	    QLatin1String("OUT")},
	{zOUTD,	    QLatin1String("OUTD")},
	{zOUTI,	    QLatin1String("OUTI")},
	{zPOP,      QLatin1String("POP")},
	{zPUSH,     QLatin1String("PUSH")},
	{zRES,      QLatin1String("RES")},
	{zRET,      QLatin1String("RET")},
	{zRETI,	    QLatin1String("RETI")},
	{zRETN,	    QLatin1String("RETN")},
	{zRL,	    QLatin1String("RL")},
	{zRLA,	    QLatin1String("RLA")},
	{zRLC,	    QLatin1String("RLC")},
	{zRLCA,	    QLatin1String("RLCA")},
	{zRLD,	    QLatin1String("RLD")},
	{zRR,	    QLatin1String("RR")},
	{zRRA,	    QLatin1String("RRA")},
	{zRRC,	    QLatin1String("RRC")},
	{zRRCA,	    QLatin1String("RRCA")},
	{zRRD,	    QLatin1String("RRD")},
	{zRST,	    QLatin1String("RST")},
	{zSBC,	    QLatin1String("SBC")},
	{zSCF,	    QLatin1String("SCF")},
	{zSET,	    QLatin1String("SET")},
	{zSLA,	    QLatin1String("SLA")},
	{zSLL,	    QLatin1String("SLL")},
	{zSRA,	    QLatin1String("SRA")},
	{zSRL,	    QLatin1String("SRL")},
	{zSUB,	    QLatin1String("SUB")},
	{zXOR,	    QLatin1String("XOR")}
	});
    return lookup.value(m);
}

quint32 z80Token::flags(Mnemonics m)
{
    static QHash<Mnemonics,quint32> flags({
	{zADC,	    0},
	{zADD,	    0},
	{zAND,	    0},
	{zBIT,	    0},
	{zCALL,	    DASMFLAG_OVER},
	{zCCF,	    0},
	{zCP,	    0},
	{zCPD,	    0},
	{zCPDR,	    DASMFLAG_OVER},
	{zCPI,	    0},
	{zCPIR,	    DASMFLAG_OVER},
	{zCPL,	    0},
	{zDAA,	    0},
	{zDB,	    0},
	{zDEC,	    0},
	{zDEFB,	    0},
	{zDEFW,	    0},
	{zDEFD,	    0},
	{zDEFM,	    0},
	{zDEFS,	    0},
	{zDI,	    0},
	{zDJNZ,	    DASMFLAG_OVER},
	{zEI,	    0},
	{zEX,	    0},
	{zEXX,	    0},
	{zHLT,	    DASMFLAG_SKIP},
	{zIM,	    0},
	{zIN,	    0},
	{zINC,	    0},
	{zIND,	    0},
	{zINDR,	    DASMFLAG_OVER},
	{zINI,	    0},
	{zINIR,	    DASMFLAG_OVER},
	{zJP,	    DASMFLAG_OVER},
	{zJR,	    DASMFLAG_OVER},
	{zLD,	    0},
	{zLDD,	    0},
	{zLDDR,	    DASMFLAG_OVER},
	{zLDI,	    0},
	{zLDIR,	    DASMFLAG_OVER},
	{zNEG,	    0},
	{zNOP,	    0},
	{zOR,	    0},
	{zOTDR,	    DASMFLAG_OVER},
	{zOTIR,	    DASMFLAG_OVER},
	{zOUT,	    0},
	{zOUTD,	    0},
	{zOUTI,	    0},
	{zPOP,	    0},
	{zPUSH,	    0},
	{zRES,	    0},
	{zRET,	    DASMFLAG_SKIP},
	{zRETI,	    DASMFLAG_SKIP},
	{zRETN,	    DASMFLAG_SKIP},
	{zRL,	    0},
	{zRLA,	    0},
	{zRLC,	    0},
	{zRLCA,	    0},
	{zRLD,	    0},
	{zRR,	    0},
	{zRRA,	    0},
	{zRRC,	    0},
	{zRRCA,	    0},
	{zRRD,	    0},
	{zRST,	    DASMFLAG_OVER},
	{zSBC,	    0},
	{zSCF,	    0},
	{zSET,	    0},
	{zSLA,	    0},
	{zSLL,	    0},
	{zSRA,	    0},
	{zSRL,	    0},
	{zSUB,	    0},
	{zXOR,	    0}
    });
    return flags.value(m);
}

z80Token z80Token::mnemonic_xx_cb(uchar op)
{
    static const QVector<z80Token> lookup({
	z80Token(zRLC,"b=Y"),
	z80Token(zRLC,"c=Y"),
	z80Token(zRLC,"d=Y"),
	z80Token(zRLC,"e=Y"),
	z80Token(zRLC,"h=Y"),
	z80Token(zRLC,"l=Y"),
	z80Token(zRLC,"Y"),
	z80Token(zRLC,"a=Y"),
	z80Token(zRRC,"b=Y"),
	z80Token(zRRC,"c=Y"),
	z80Token(zRRC,"d=Y"),
	z80Token(zRRC,"e=Y"),
	z80Token(zRRC,"h=Y"),
	z80Token(zRRC,"l=Y"),
	z80Token(zRRC,"Y"),
	z80Token(zRRC,"a=Y"),
	z80Token(zRL,"b=Y"),
	z80Token(zRL,"c=Y"),
	z80Token(zRL,"d=Y"),
	z80Token(zRL,"e=Y"),
	z80Token(zRL,"h=Y"),
	z80Token(zRL,"l=Y"),
	z80Token(zRL,"Y"),
	z80Token(zRL,"a=Y"),
	z80Token(zRR,"b=Y"),
	z80Token(zRR,"c=Y"),
	z80Token(zRR,"d=Y"),
	z80Token(zRR,"e=Y"),
	z80Token(zRR,"h=Y"),
	z80Token(zRR,"l=Y"),
	z80Token(zRR,"Y"),
	z80Token(zRR,"a=Y"),
	z80Token(zSLA,"b=Y"),
	z80Token(zSLA,"c=Y"),
	z80Token(zSLA,"d=Y"),
	z80Token(zSLA,"e=Y"),
	z80Token(zSLA,"h=Y"),
	z80Token(zSLA,"l=Y"),
	z80Token(zSLA,"Y"),
	z80Token(zSLA,"a=Y"),
	z80Token(zSRA,"b=Y"),
	z80Token(zSRA,"c=Y"),
	z80Token(zSRA,"d=Y"),
	z80Token(zSRA,"e=Y"),
	z80Token(zSRA,"h=Y"),
	z80Token(zSRA,"l=Y"),
	z80Token(zSRA,"Y"),
	z80Token(zSRA,"a=Y"),
	z80Token(zSLL,"b=Y"),
	z80Token(zSLL,"c=Y"),
	z80Token(zSLL,"d=Y"),
	z80Token(zSLL,"e=Y"),
	z80Token(zSLL,"h=Y"),
	z80Token(zSLL,"l=Y"),
	z80Token(zSLL,"Y"),
	z80Token(zSLL,"a=Y"),
	z80Token(zSRL,"b=Y"),
	z80Token(zSRL,"c=Y"),
	z80Token(zSRL,"d=Y"),
	z80Token(zSRL,"e=Y"),
	z80Token(zSRL,"h=Y"),
	z80Token(zSRL,"l=Y"),
	z80Token(zSRL,"Y"),
	z80Token(zSRL,"a=Y"),
	z80Token(zBIT,"0,Y"),
	z80Token(zBIT,"0,Y"),
	z80Token(zBIT,"0,Y"),
	z80Token(zBIT,"0,Y"),
	z80Token(zBIT,"0,Y"),
	z80Token(zBIT,"0,Y"),
	z80Token(zBIT,"0,Y"),
	z80Token(zBIT,"0,Y"),
	z80Token(zBIT,"1,Y"),
	z80Token(zBIT,"1,Y"),
	z80Token(zBIT,"1,Y"),
	z80Token(zBIT,"1,Y"),
	z80Token(zBIT,"1,Y"),
	z80Token(zBIT,"1,Y"),
	z80Token(zBIT,"1,Y"),
	z80Token(zBIT,"1,Y"),
	z80Token(zBIT,"2,Y"),
	z80Token(zBIT,"2,Y"),
	z80Token(zBIT,"2,Y"),
	z80Token(zBIT,"2,Y"),
	z80Token(zBIT,"2,Y"),
	z80Token(zBIT,"2,Y"),
	z80Token(zBIT,"2,Y"),
	z80Token(zBIT,"2,Y"),
	z80Token(zBIT,"3,Y"),
	z80Token(zBIT,"3,Y"),
	z80Token(zBIT,"3,Y"),
	z80Token(zBIT,"3,Y"),
	z80Token(zBIT,"3,Y"),
	z80Token(zBIT,"3,Y"),
	z80Token(zBIT,"3,Y"),
	z80Token(zBIT,"3,Y"),
	z80Token(zBIT,"4,Y"),
	z80Token(zBIT,"4,Y"),
	z80Token(zBIT,"4,Y"),
	z80Token(zBIT,"4,Y"),
	z80Token(zBIT,"4,Y"),
	z80Token(zBIT,"4,Y"),
	z80Token(zBIT,"4,Y"),
	z80Token(zBIT,"4,Y"),
	z80Token(zBIT,"5,Y"),
	z80Token(zBIT,"5,Y"),
	z80Token(zBIT,"5,Y"),
	z80Token(zBIT,"5,Y"),
	z80Token(zBIT,"5,Y"),
	z80Token(zBIT,"5,Y"),
	z80Token(zBIT,"5,Y"),
	z80Token(zBIT,"5,Y"),
	z80Token(zBIT,"6,Y"),
	z80Token(zBIT,"6,Y"),
	z80Token(zBIT,"6,Y"),
	z80Token(zBIT,"6,Y"),
	z80Token(zBIT,"6,Y"),
	z80Token(zBIT,"6,Y"),
	z80Token(zBIT,"6,Y"),
	z80Token(zBIT,"6,Y"),
	z80Token(zBIT,"7,Y"),
	z80Token(zBIT,"7,Y"),
	z80Token(zBIT,"7,Y"),
	z80Token(zBIT,"7,Y"),
	z80Token(zBIT,"7,Y"),
	z80Token(zBIT,"7,Y"),
	z80Token(zBIT,"7,Y"),
	z80Token(zBIT,"7,Y"),
	z80Token(zRES,"b=0,Y"),
	z80Token(zRES,"c=0,Y"),
	z80Token(zRES,"d=0,Y"),
	z80Token(zRES,"e=0,Y"),
	z80Token(zRES,"h=0,Y"),
	z80Token(zRES,"l=0,Y"),
	z80Token(zRES,"0,Y"),
	z80Token(zRES,"a=0,Y"),
	z80Token(zRES,"b=1,Y"),
	z80Token(zRES,"c=1,Y"),
	z80Token(zRES,"d=1,Y"),
	z80Token(zRES,"e=1,Y"),
	z80Token(zRES,"h=1,Y"),
	z80Token(zRES,"l=1,Y"),
	z80Token(zRES,"1,Y"),
	z80Token(zRES,"a=1,Y"),
	z80Token(zRES,"b=2,Y"),
	z80Token(zRES,"c=2,Y"),
	z80Token(zRES,"d=2,Y"),
	z80Token(zRES,"e=2,Y"),
	z80Token(zRES,"h=2,Y"),
	z80Token(zRES,"l=2,Y"),
	z80Token(zRES,"2,Y"),
	z80Token(zRES,"a=2,Y"),
	z80Token(zRES,"b=3,Y"),
	z80Token(zRES,"c=3,Y"),
	z80Token(zRES,"d=3,Y"),
	z80Token(zRES,"e=3,Y"),
	z80Token(zRES,"h=3,Y"),
	z80Token(zRES,"l=3,Y"),
	z80Token(zRES,"3,Y"),
	z80Token(zRES,"a=3,Y"),
	z80Token(zRES,"b=4,Y"),
	z80Token(zRES,"c=4,Y"),
	z80Token(zRES,"d=4,Y"),
	z80Token(zRES,"e=4,Y"),
	z80Token(zRES,"h=4,Y"),
	z80Token(zRES,"l=4,Y"),
	z80Token(zRES,"4,Y"),
	z80Token(zRES,"a=4,Y"),
	z80Token(zRES,"b=5,Y"),
	z80Token(zRES,"c=5,Y"),
	z80Token(zRES,"d=5,Y"),
	z80Token(zRES,"e=5,Y"),
	z80Token(zRES,"h=5,Y"),
	z80Token(zRES,"l=5,Y"),
	z80Token(zRES,"5,Y"),
	z80Token(zRES,"a=5,Y"),
	z80Token(zRES,"b=6,Y"),
	z80Token(zRES,"c=6,Y"),
	z80Token(zRES,"d=6,Y"),
	z80Token(zRES,"e=6,Y"),
	z80Token(zRES,"h=6,Y"),
	z80Token(zRES,"l=6,Y"),
	z80Token(zRES,"6,Y"),
	z80Token(zRES,"a=6,Y"),
	z80Token(zRES,"b=7,Y"),
	z80Token(zRES,"c=7,Y"),
	z80Token(zRES,"d=7,Y"),
	z80Token(zRES,"e=7,Y"),
	z80Token(zRES,"h=7,Y"),
	z80Token(zRES,"l=7,Y"),
	z80Token(zRES,"7,Y"),
	z80Token(zRES,"a=7,Y"),
	z80Token(zSET,"b=0,Y"),
	z80Token(zSET,"c=0,Y"),
	z80Token(zSET,"d=0,Y"),
	z80Token(zSET,"e=0,Y"),
	z80Token(zSET,"h=0,Y"),
	z80Token(zSET,"l=0,Y"),
	z80Token(zSET,"0,Y"),
	z80Token(zSET,"a=0,Y"),
	z80Token(zSET,"b=1,Y"),
	z80Token(zSET,"c=1,Y"),
	z80Token(zSET,"d=1,Y"),
	z80Token(zSET,"e=1,Y"),
	z80Token(zSET,"h=1,Y"),
	z80Token(zSET,"l=1,Y"),
	z80Token(zSET,"1,Y"),
	z80Token(zSET,"a=1,Y"),
	z80Token(zSET,"b=2,Y"),
	z80Token(zSET,"c=2,Y"),
	z80Token(zSET,"d=2,Y"),
	z80Token(zSET,"e=2,Y"),
	z80Token(zSET,"h=2,Y"),
	z80Token(zSET,"l=2,Y"),
	z80Token(zSET,"2,Y"),
	z80Token(zSET,"a=2,Y"),
	z80Token(zSET,"b=3,Y"),
	z80Token(zSET,"c=3,Y"),
	z80Token(zSET,"d=3,Y"),
	z80Token(zSET,"e=3,Y"),
	z80Token(zSET,"h=3,Y"),
	z80Token(zSET,"l=3,Y"),
	z80Token(zSET,"3,Y"),
	z80Token(zSET,"a=3,Y"),
	z80Token(zSET,"b=4,Y"),
	z80Token(zSET,"c=4,Y"),
	z80Token(zSET,"d=4,Y"),
	z80Token(zSET,"e=4,Y"),
	z80Token(zSET,"h=4,Y"),
	z80Token(zSET,"l=4,Y"),
	z80Token(zSET,"4,Y"),
	z80Token(zSET,"a=4,Y"),
	z80Token(zSET,"b=5,Y"),
	z80Token(zSET,"c=5,Y"),
	z80Token(zSET,"d=5,Y"),
	z80Token(zSET,"e=5,Y"),
	z80Token(zSET,"h=5,Y"),
	z80Token(zSET,"l=5,Y"),
	z80Token(zSET,"5,Y"),
	z80Token(zSET,"a=5,Y"),
	z80Token(zSET,"b=6,Y"),
	z80Token(zSET,"c=6,Y"),
	z80Token(zSET,"d=6,Y"),
	z80Token(zSET,"e=6,Y"),
	z80Token(zSET,"h=6,Y"),
	z80Token(zSET,"l=6,Y"),
	z80Token(zSET,"6,Y"),
	z80Token(zSET,"a=6,Y"),
	z80Token(zSET,"b=7,Y"),
	z80Token(zSET,"c=7,Y"),
	z80Token(zSET,"d=7,Y"),
	z80Token(zSET,"e=7,Y"),
	z80Token(zSET,"h=7,Y"),
	z80Token(zSET,"l=7,Y"),
	z80Token(zSET,"7,Y"),
	z80Token(zSET,"a=7,Y")
    });
    return lookup.value(op);
}

z80Token z80Token::mnemonic_cb(uchar op)
{
    static const QVector<z80Token> lookup({
	z80Token(zRLC,"b"),
	z80Token(zRLC,"c"),
	z80Token(zRLC,"d"),
	z80Token(zRLC,"e"),
	z80Token(zRLC,"h"),
	z80Token(zRLC,"l"),
	z80Token(zRLC,"(hl)"),
	z80Token(zRLC,"a"),
	z80Token(zRRC,"b"),
	z80Token(zRRC,"c"),
	z80Token(zRRC,"d"),
	z80Token(zRRC,"e"),
	z80Token(zRRC,"h"),
	z80Token(zRRC,"l"),
	z80Token(zRRC,"(hl)"),
	z80Token(zRRC,"a"),
	z80Token(zRL,"b"),
	z80Token(zRL,"c"),
	z80Token(zRL,"d"),
	z80Token(zRL,"e"),
	z80Token(zRL,"h"),
	z80Token(zRL,"l"),
	z80Token(zRL,"(hl)"),
	z80Token(zRL,"a"),
	z80Token(zRR,"b"),
	z80Token(zRR,"c"),
	z80Token(zRR,"d"),
	z80Token(zRR,"e"),
	z80Token(zRR,"h"),
	z80Token(zRR,"l"),
	z80Token(zRR,"(hl)"),
	z80Token(zRR,"a"),
	z80Token(zSLA,"b"),
	z80Token(zSLA,"c"),
	z80Token(zSLA,"d"),
	z80Token(zSLA,"e"),
	z80Token(zSLA,"h"),
	z80Token(zSLA,"l"),
	z80Token(zSLA,"(hl)"),
	z80Token(zSLA,"a"),
	z80Token(zSRA,"b"),
	z80Token(zSRA,"c"),
	z80Token(zSRA,"d"),
	z80Token(zSRA,"e"),
	z80Token(zSRA,"h"),
	z80Token(zSRA,"l"),
	z80Token(zSRA,"(hl)"),
	z80Token(zSRA,"a"),
	z80Token(zSLL,"b"),
	z80Token(zSLL,"c"),
	z80Token(zSLL,"d"),
	z80Token(zSLL,"e"),
	z80Token(zSLL,"h"),
	z80Token(zSLL,"l"),
	z80Token(zSLL,"(hl)"),
	z80Token(zSLL,"a"),
	z80Token(zSRL,"b"),
	z80Token(zSRL,"c"),
	z80Token(zSRL,"d"),
	z80Token(zSRL,"e"),
	z80Token(zSRL,"h"),
	z80Token(zSRL,"l"),
	z80Token(zSRL,"(hl)"),
	z80Token(zSRL,"a"),
	z80Token(zBIT,"0,b"),
	z80Token(zBIT,"0,c"),
	z80Token(zBIT,"0,d"),
	z80Token(zBIT,"0,e"),
	z80Token(zBIT,"0,h"),
	z80Token(zBIT,"0,l"),
	z80Token(zBIT,"0,(hl)"),
	z80Token(zBIT,"0,a"),
	z80Token(zBIT,"1,b"),
	z80Token(zBIT,"1,c"),
	z80Token(zBIT,"1,d"),
	z80Token(zBIT,"1,e"),
	z80Token(zBIT,"1,h"),
	z80Token(zBIT,"1,l"),
	z80Token(zBIT,"1,(hl)"),
	z80Token(zBIT,"1,a"),
	z80Token(zBIT,"2,b"),
	z80Token(zBIT,"2,c"),
	z80Token(zBIT,"2,d"),
	z80Token(zBIT,"2,e"),
	z80Token(zBIT,"2,h"),
	z80Token(zBIT,"2,l"),
	z80Token(zBIT,"2,(hl)"),
	z80Token(zBIT,"2,a"),
	z80Token(zBIT,"3,b"),
	z80Token(zBIT,"3,c"),
	z80Token(zBIT,"3,d"),
	z80Token(zBIT,"3,e"),
	z80Token(zBIT,"3,h"),
	z80Token(zBIT,"3,l"),
	z80Token(zBIT,"3,(hl)"),
	z80Token(zBIT,"3,a"),
	z80Token(zBIT,"4,b"),
	z80Token(zBIT,"4,c"),
	z80Token(zBIT,"4,d"),
	z80Token(zBIT,"4,e"),
	z80Token(zBIT,"4,h"),
	z80Token(zBIT,"4,l"),
	z80Token(zBIT,"4,(hl)"),
	z80Token(zBIT,"4,a"),
	z80Token(zBIT,"5,b"),
	z80Token(zBIT,"5,c"),
	z80Token(zBIT,"5,d"),
	z80Token(zBIT,"5,e"),
	z80Token(zBIT,"5,h"),
	z80Token(zBIT,"5,l"),
	z80Token(zBIT,"5,(hl)"),
	z80Token(zBIT,"5,a"),
	z80Token(zBIT,"6,b"),
	z80Token(zBIT,"6,c"),
	z80Token(zBIT,"6,d"),
	z80Token(zBIT,"6,e"),
	z80Token(zBIT,"6,h"),
	z80Token(zBIT,"6,l"),
	z80Token(zBIT,"6,(hl)"),
	z80Token(zBIT,"6,a"),
	z80Token(zBIT,"7,b"),
	z80Token(zBIT,"7,c"),
	z80Token(zBIT,"7,d"),
	z80Token(zBIT,"7,e"),
	z80Token(zBIT,"7,h"),
	z80Token(zBIT,"7,l"),
	z80Token(zBIT,"7,(hl)"),
	z80Token(zBIT,"7,a"),
	z80Token(zRES,"0,b"),
	z80Token(zRES,"0,c"),
	z80Token(zRES,"0,d"),
	z80Token(zRES,"0,e"),
	z80Token(zRES,"0,h"),
	z80Token(zRES,"0,l"),
	z80Token(zRES,"0,(hl)"),
	z80Token(zRES,"0,a"),
	z80Token(zRES,"1,b"),
	z80Token(zRES,"1,c"),
	z80Token(zRES,"1,d"),
	z80Token(zRES,"1,e"),
	z80Token(zRES,"1,h"),
	z80Token(zRES,"1,l"),
	z80Token(zRES,"1,(hl)"),
	z80Token(zRES,"1,a"),
	z80Token(zRES,"2,b"),
	z80Token(zRES,"2,c"),
	z80Token(zRES,"2,d"),
	z80Token(zRES,"2,e"),
	z80Token(zRES,"2,h"),
	z80Token(zRES,"2,l"),
	z80Token(zRES,"2,(hl)"),
	z80Token(zRES,"2,a"),
	z80Token(zRES,"3,b"),
	z80Token(zRES,"3,c"),
	z80Token(zRES,"3,d"),
	z80Token(zRES,"3,e"),
	z80Token(zRES,"3,h"),
	z80Token(zRES,"3,l"),
	z80Token(zRES,"3,(hl)"),
	z80Token(zRES,"3,a"),
	z80Token(zRES,"4,b"),
	z80Token(zRES,"4,c"),
	z80Token(zRES,"4,d"),
	z80Token(zRES,"4,e"),
	z80Token(zRES,"4,h"),
	z80Token(zRES,"4,l"),
	z80Token(zRES,"4,(hl)"),
	z80Token(zRES,"4,a"),
	z80Token(zRES,"5,b"),
	z80Token(zRES,"5,c"),
	z80Token(zRES,"5,d"),
	z80Token(zRES,"5,e"),
	z80Token(zRES,"5,h"),
	z80Token(zRES,"5,l"),
	z80Token(zRES,"5,(hl)"),
	z80Token(zRES,"5,a"),
	z80Token(zRES,"6,b"),
	z80Token(zRES,"6,c"),
	z80Token(zRES,"6,d"),
	z80Token(zRES,"6,e"),
	z80Token(zRES,"6,h"),
	z80Token(zRES,"6,l"),
	z80Token(zRES,"6,(hl)"),
	z80Token(zRES,"6,a"),
	z80Token(zRES,"7,b"),
	z80Token(zRES,"7,c"),
	z80Token(zRES,"7,d"),
	z80Token(zRES,"7,e"),
	z80Token(zRES,"7,h"),
	z80Token(zRES,"7,l"),
	z80Token(zRES,"7,(hl)"),
	z80Token(zRES,"7,a"),
	z80Token(zSET,"0,b"),
	z80Token(zSET,"0,c"),
	z80Token(zSET,"0,d"),
	z80Token(zSET,"0,e"),
	z80Token(zSET,"0,h"),
	z80Token(zSET,"0,l"),
	z80Token(zSET,"0,(hl)"),
	z80Token(zSET,"0,a"),
	z80Token(zSET,"1,b"),
	z80Token(zSET,"1,c"),
	z80Token(zSET,"1,d"),
	z80Token(zSET,"1,e"),
	z80Token(zSET,"1,h"),
	z80Token(zSET,"1,l"),
	z80Token(zSET,"1,(hl)"),
	z80Token(zSET,"1,a"),
	z80Token(zSET,"2,b"),
	z80Token(zSET,"2,c"),
	z80Token(zSET,"2,d"),
	z80Token(zSET,"2,e"),
	z80Token(zSET,"2,h"),
	z80Token(zSET,"2,l"),
	z80Token(zSET,"2,(hl)"),
	z80Token(zSET,"2,a"),
	z80Token(zSET,"3,b"),
	z80Token(zSET,"3,c"),
	z80Token(zSET,"3,d"),
	z80Token(zSET,"3,e"),
	z80Token(zSET,"3,h"),
	z80Token(zSET,"3,l"),
	z80Token(zSET,"3,(hl)"),
	z80Token(zSET,"3,a"),
	z80Token(zSET,"4,b"),
	z80Token(zSET,"4,c"),
	z80Token(zSET,"4,d"),
	z80Token(zSET,"4,e"),
	z80Token(zSET,"4,h"),
	z80Token(zSET,"4,l"),
	z80Token(zSET,"4,(hl)"),
	z80Token(zSET,"4,a"),
	z80Token(zSET,"5,b"),
	z80Token(zSET,"5,c"),
	z80Token(zSET,"5,d"),
	z80Token(zSET,"5,e"),
	z80Token(zSET,"5,h"),
	z80Token(zSET,"5,l"),
	z80Token(zSET,"5,(hl)"),
	z80Token(zSET,"5,a"),
	z80Token(zSET,"6,b"),
	z80Token(zSET,"6,c"),
	z80Token(zSET,"6,d"),
	z80Token(zSET,"6,e"),
	z80Token(zSET,"6,h"),
	z80Token(zSET,"6,l"),
	z80Token(zSET,"6,(hl)"),
	z80Token(zSET,"6,a"),
	z80Token(zSET,"7,b"),
	z80Token(zSET,"7,c"),
	z80Token(zSET,"7,d"),
	z80Token(zSET,"7,e"),
	z80Token(zSET,"7,h"),
	z80Token(zSET,"7,l"),
	z80Token(zSET,"7,(hl)"),
	z80Token(zSET,"7,a")
    });

    return lookup.value(op);
}

z80Token z80Token::mnemonic_ed(uchar op)
{
    static const QVector<z80Token> lookup({
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zIN,"b,(c)"),
	z80Token(zOUT,"(c),b"),
	z80Token(zSBC,"hl,bc"),
	z80Token(zLD,"(W),bc"),
	z80Token(zNEG,NULL),
	z80Token(zRETN,NULL),
	z80Token(zIM,"0"),
	z80Token(zLD,"i,a"),
	z80Token(zIN,"c,(c)"),
	z80Token(zOUT,"(c),c"),
	z80Token(zADC,"hl,bc"),
	z80Token(zLD,"bc,(W)"),
	z80Token(zNEG,"*"),
	z80Token(zRETI,NULL),
	z80Token(zIM,"0"),
	z80Token(zLD,"r,a"),
	z80Token(zIN,"d,(c)"),
	z80Token(zOUT,"(c),d"),
	z80Token(zSBC,"hl,de"),
	z80Token(zLD,"(W),de"),
	z80Token(zNEG,"*"),
	z80Token(zRETN,"*"),
	z80Token(zIM,"1"),
	z80Token(zLD,"a,i"),
	z80Token(zIN,"e,(c)"),
	z80Token(zOUT,"(c),e"),
	z80Token(zADC,"hl,de"),
	z80Token(zLD,"de,(W)"),
	z80Token(zNEG,"*"),
	z80Token(zRETI,"*"),
	z80Token(zIM,"2"),
	z80Token(zLD,"a,r"),
	z80Token(zIN,"h,(c)"),
	z80Token(zOUT,"(c),h"),
	z80Token(zSBC,"hl,hl"),
	z80Token(zLD,"(W),hl"),
	z80Token(zNEG,"*"),
	z80Token(zRETN,"*"),
	z80Token(zIM,"0"),
	z80Token(zRRD,"(hl)"),
	z80Token(zIN,"l,(c)"),
	z80Token(zOUT,"(c),l"),
	z80Token(zADC,"hl,hl"),
	z80Token(zLD,"hl,(W)"),
	z80Token(zNEG,"*"),
	z80Token(zRETI,"*"),
	z80Token(zIM,"0"),
	z80Token(zRLD,"(hl)"),
	z80Token(zIN,"0,(c)"),
	z80Token(zOUT,"(c),0"),
	z80Token(zSBC,"hl,sp"),
	z80Token(zLD,"(W),sp"),
	z80Token(zNEG,"*"),
	z80Token(zRETN,"*"),
	z80Token(zIM,"1"),
	z80Token(zDB,"?"),
	z80Token(zIN,"a,(c)"),
	z80Token(zOUT,"(c),a"),
	z80Token(zADC,"hl,sp"),
	z80Token(zLD,"sp,(W)"),
	z80Token(zNEG,"*"),
	z80Token(zRETI,"*"),
	z80Token(zIM,"2"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zLDI,NULL),
	z80Token(zCPI,NULL),
	z80Token(zINI,NULL),
	z80Token(zOUTI,NULL),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zLDD,NULL),
	z80Token(zCPD,NULL),
	z80Token(zIND,NULL),
	z80Token(zOUTD,NULL),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zLDIR,NULL),
	z80Token(zCPIR,NULL),
	z80Token(zINIR,NULL),
	z80Token(zOTIR,NULL),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zLDDR,NULL),
	z80Token(zCPDR,NULL),
	z80Token(zINDR,NULL),
	z80Token(zOTDR,NULL),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?")
    });

    return lookup.value(op);
}

z80Token z80Token::mnemonic_xx(uchar op)
{
    static const QVector<z80Token> lookup({
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zADD,"I,bc"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zADD,"I,de"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zLD,"I,N"),
	z80Token(zLD,"(W),I"),
	z80Token(zINC,"I"),
	z80Token(zINC,"Ih"),
	z80Token(zDEC,"Ih"),
	z80Token(zLD,"Ih,B"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zADD,"I,I"),
	z80Token(zLD,"I,(W)"),
	z80Token(zDEC,"I"),
	z80Token(zINC,"Il"),
	z80Token(zDEC,"Il"),
	z80Token(zLD,"Il,B"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zINC,"X"),
	z80Token(zDEC,"X"),
	z80Token(zLD,"X,B"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zADD,"I,sp"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zLD,"b,Ih"),
	z80Token(zLD,"b,Il"),
	z80Token(zLD,"b,X"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zLD,"c,Ih"),
	z80Token(zLD,"c,Il"),
	z80Token(zLD,"c,X"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zLD,"d,Ih"),
	z80Token(zLD,"d,Il"),
	z80Token(zLD,"d,X"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zLD,"e,Ih"),
	z80Token(zLD,"e,Il"),
	z80Token(zLD,"e,X"),
	z80Token(zDB,"?"),
	z80Token(zLD,"Ih,b"),
	z80Token(zLD,"Ih,c"),
	z80Token(zLD,"Ih,d"),
	z80Token(zLD,"Ih,e"),
	z80Token(zLD,"Ih,Ih"),
	z80Token(zLD,"Ih,Il"),
	z80Token(zLD,"h,X"),
	z80Token(zLD,"Ih,a"),
	z80Token(zLD,"Il,b"),
	z80Token(zLD,"Il,c"),
	z80Token(zLD,"Il,d"),
	z80Token(zLD,"Il,e"),
	z80Token(zLD,"Il,Ih"),
	z80Token(zLD,"Il,Il"),
	z80Token(zLD,"l,X"),
	z80Token(zLD,"Il,a"),
	z80Token(zLD,"X,b"),
	z80Token(zLD,"X,c"),
	z80Token(zLD,"X,d"),
	z80Token(zLD,"X,e"),
	z80Token(zLD,"X,h"),
	z80Token(zLD,"X,l"),
	z80Token(zDB,"?"),
	z80Token(zLD,"X,a"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zLD,"a,Ih"),
	z80Token(zLD,"a,Il"),
	z80Token(zLD,"a,X"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zADD,"a,Ih"),
	z80Token(zADD,"a,Il"),
	z80Token(zADD,"a,X"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zADC,"a,Ih"),
	z80Token(zADC,"a,Il"),
	z80Token(zADC,"a,X"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zSUB,"Ih"),
	z80Token(zSUB,"Il"),
	z80Token(zSUB,"X"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zSBC,"a,Ih"),
	z80Token(zSBC,"a,Il"),
	z80Token(zSBC,"a,X"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zAND,"Ih"),
	z80Token(zAND,"Il"),
	z80Token(zAND,"X"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zXOR,"Ih"),
	z80Token(zXOR,"Il"),
	z80Token(zXOR,"X"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zOR,"Ih"),
	z80Token(zOR,"Il"),
	z80Token(zOR,"X"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zCP,"Ih"),
	z80Token(zCP,"Il"),
	z80Token(zCP,"X"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"cb"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zPOP,"I"),
	z80Token(zDB,"?"),
	z80Token(zEX,"(sp),I"),
	z80Token(zDB,"?"),
	z80Token(zPUSH,"I"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zJP,"(I)"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zLD,"sp,I"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?"),
	z80Token(zDB,"?")
    });
    return lookup.value(op);
}

z80Token z80Token::mnemonic_main(uchar op)
{
    static const QVector<z80Token> lookup({
	z80Token(zNOP,NULL),
	z80Token(zLD,"bc,N"),
	z80Token(zLD,"(bc),a"),
	z80Token(zINC,"bc"),
	z80Token(zINC,"b"),
	z80Token(zDEC,"b"),
	z80Token(zLD,"b,B"),
	z80Token(zRLCA,NULL),
	z80Token(zEX,"af,af'"),
	z80Token(zADD,"hl,bc"),
	z80Token(zLD,"a,(bc)"),
	z80Token(zDEC,"bc"),
	z80Token(zINC,"c"),
	z80Token(zDEC,"c"),
	z80Token(zLD,"c,B"),
	z80Token(zRRCA,NULL),
	z80Token(zDJNZ,"O"),
	z80Token(zLD,"de,N"),
	z80Token(zLD,"(de),a"),
	z80Token(zINC,"de"),
	z80Token(zINC,"d"),
	z80Token(zDEC,"d"),
	z80Token(zLD,"d,B"),
	z80Token(zRLA,NULL),
	z80Token(zJR,"O"),
	z80Token(zADD,"hl,de"),
	z80Token(zLD,"a,(de)"),
	z80Token(zDEC,"de"),
	z80Token(zINC,"e"),
	z80Token(zDEC,"e"),
	z80Token(zLD,"e,B"),
	z80Token(zRRA,NULL),
	z80Token(zJR,"nz,O"),
	z80Token(zLD,"hl,N"),
	z80Token(zLD,"(W),hl"),
	z80Token(zINC,"hl"),
	z80Token(zINC,"h"),
	z80Token(zDEC,"h"),
	z80Token(zLD,"h,B"),
	z80Token(zDAA,NULL),
	z80Token(zJR,"z,O"),
	z80Token(zADD,"hl,hl"),
	z80Token(zLD,"hl,(W)"),
	z80Token(zDEC,"hl"),
	z80Token(zINC,"l"),
	z80Token(zDEC,"l"),
	z80Token(zLD,"l,B"),
	z80Token(zCPL,NULL),
	z80Token(zJR,"nc,O"),
	z80Token(zLD,"sp,N"),
	z80Token(zLD,"(W),a"),
	z80Token(zINC,"sp"),
	z80Token(zINC,"(hl)"),
	z80Token(zDEC,"(hl)"),
	z80Token(zLD,"(hl),B"),
	z80Token(zSCF,NULL),
	z80Token(zJR,"c,O"),
	z80Token(zADD,"hl,sp"),
	z80Token(zLD,"a,(W)"),
	z80Token(zDEC,"sp"),
	z80Token(zINC,"a"),
	z80Token(zDEC,"a"),
	z80Token(zLD,"a,B"),
	z80Token(zCCF,NULL),
	z80Token(zLD,"b,b"),
	z80Token(zLD,"b,c"),
	z80Token(zLD,"b,d"),
	z80Token(zLD,"b,e"),
	z80Token(zLD,"b,h"),
	z80Token(zLD,"b,l"),
	z80Token(zLD,"b,(hl)"),
	z80Token(zLD,"b,a"),
	z80Token(zLD,"c,b"),
	z80Token(zLD,"c,c"),
	z80Token(zLD,"c,d"),
	z80Token(zLD,"c,e"),
	z80Token(zLD,"c,h"),
	z80Token(zLD,"c,l"),
	z80Token(zLD,"c,(hl)"),
	z80Token(zLD,"c,a"),
	z80Token(zLD,"d,b"),
	z80Token(zLD,"d,c"),
	z80Token(zLD,"d,d"),
	z80Token(zLD,"d,e"),
	z80Token(zLD,"d,h"),
	z80Token(zLD,"d,l"),
	z80Token(zLD,"d,(hl)"),
	z80Token(zLD,"d,a"),
	z80Token(zLD,"e,b"),
	z80Token(zLD,"e,c"),
	z80Token(zLD,"e,d"),
	z80Token(zLD,"e,e"),
	z80Token(zLD,"e,h"),
	z80Token(zLD,"e,l"),
	z80Token(zLD,"e,(hl)"),
	z80Token(zLD,"e,a"),
	z80Token(zLD,"h,b"),
	z80Token(zLD,"h,c"),
	z80Token(zLD,"h,d"),
	z80Token(zLD,"h,e"),
	z80Token(zLD,"h,h"),
	z80Token(zLD,"h,l"),
	z80Token(zLD,"h,(hl)"),
	z80Token(zLD,"h,a"),
	z80Token(zLD,"l,b"),
	z80Token(zLD,"l,c"),
	z80Token(zLD,"l,d"),
	z80Token(zLD,"l,e"),
	z80Token(zLD,"l,h"),
	z80Token(zLD,"l,l"),
	z80Token(zLD,"l,(hl)"),
	z80Token(zLD,"l,a"),
	z80Token(zLD,"(hl),b"),
	z80Token(zLD,"(hl),c"),
	z80Token(zLD,"(hl),d"),
	z80Token(zLD,"(hl),e"),
	z80Token(zLD,"(hl),h"),
	z80Token(zLD,"(hl),l"),
	z80Token(zHLT,NULL),
	z80Token(zLD,"(hl),a"),
	z80Token(zLD,"a,b"),
	z80Token(zLD,"a,c"),
	z80Token(zLD,"a,d"),
	z80Token(zLD,"a,e"),
	z80Token(zLD,"a,h"),
	z80Token(zLD,"a,l"),
	z80Token(zLD,"a,(hl)"),
	z80Token(zLD,"a,a"),
	z80Token(zADD,"a,b"),
	z80Token(zADD,"a,c"),
	z80Token(zADD,"a,d"),
	z80Token(zADD,"a,e"),
	z80Token(zADD,"a,h"),
	z80Token(zADD,"a,l"),
	z80Token(zADD,"a,(hl)"),
	z80Token(zADD,"a,a"),
	z80Token(zADC,"a,b"),
	z80Token(zADC,"a,c"),
	z80Token(zADC,"a,d"),
	z80Token(zADC,"a,e"),
	z80Token(zADC,"a,h"),
	z80Token(zADC,"a,l"),
	z80Token(zADC,"a,(hl)"),
	z80Token(zADC,"a,a"),
	z80Token(zSUB,"b"),
	z80Token(zSUB,"c"),
	z80Token(zSUB,"d"),
	z80Token(zSUB,"e"),
	z80Token(zSUB,"h"),
	z80Token(zSUB,"l"),
	z80Token(zSUB,"(hl)"),
	z80Token(zSUB,"a"),
	z80Token(zSBC,"a,b"),
	z80Token(zSBC,"a,c"),
	z80Token(zSBC,"a,d"),
	z80Token(zSBC,"a,e"),
	z80Token(zSBC,"a,h"),
	z80Token(zSBC,"a,l"),
	z80Token(zSBC,"a,(hl)"),
	z80Token(zSBC,"a,a"),
	z80Token(zAND,"b"),
	z80Token(zAND,"c"),
	z80Token(zAND,"d"),
	z80Token(zAND,"e"),
	z80Token(zAND,"h"),
	z80Token(zAND,"l"),
	z80Token(zAND,"(hl)"),
	z80Token(zAND,"a"),
	z80Token(zXOR,"b"),
	z80Token(zXOR,"c"),
	z80Token(zXOR,"d"),
	z80Token(zXOR,"e"),
	z80Token(zXOR,"h"),
	z80Token(zXOR,"l"),
	z80Token(zXOR,"(hl)"),
	z80Token(zXOR,"a"),
	z80Token(zOR,"b"),
	z80Token(zOR,"c"),
	z80Token(zOR,"d"),
	z80Token(zOR,"e"),
	z80Token(zOR,"h"),
	z80Token(zOR,"l"),
	z80Token(zOR,"(hl)"),
	z80Token(zOR,"a"),
	z80Token(zCP,"b"),
	z80Token(zCP,"c"),
	z80Token(zCP,"d"),
	z80Token(zCP,"e"),
	z80Token(zCP,"h"),
	z80Token(zCP,"l"),
	z80Token(zCP,"(hl)"),
	z80Token(zCP,"a"),
	z80Token(zRET,"nz"),
	z80Token(zPOP,"bc"),
	z80Token(zJP,"nz,A"),
	z80Token(zJP,"A"),
	z80Token(zCALL,"nz,A"),
	z80Token(zPUSH,"bc"),
	z80Token(zADD,"a,B"),
	z80Token(zRST,"V"),
	z80Token(zRET,"z"),
	z80Token(zRET,NULL),
	z80Token(zJP,"z,A"),
	z80Token(zDB,"cb"),
	z80Token(zCALL,"z,A"),
	z80Token(zCALL,"A"),
	z80Token(zADC,"a,B"),
	z80Token(zRST,"V"),
	z80Token(zRET,"nc"),
	z80Token(zPOP,"de"),
	z80Token(zJP,"nc,A"),
	z80Token(zOUT,"(P),a"),
	z80Token(zCALL,"nc,A"),
	z80Token(zPUSH,"de"),
	z80Token(zSUB,"B"),
	z80Token(zRST,"V"),
	z80Token(zRET,"c"),
	z80Token(zEXX,NULL),
	z80Token(zJP,"c,A"),
	z80Token(zIN,"a,(P)"),
	z80Token(zCALL,"c,A"),
	z80Token(zDB,"dd"),
	z80Token(zSBC,"a,B"),
	z80Token(zRST,"V"),
	z80Token(zRET,"po"),
	z80Token(zPOP,"hl"),
	z80Token(zJP,"po,A"),
	z80Token(zEX,"(sp),hl"),
	z80Token(zCALL,"po,A"),
	z80Token(zPUSH,"hl"),
	z80Token(zAND,"B"),
	z80Token(zRST,"V"),
	z80Token(zRET,"pe"),
	z80Token(zJP,"(hl)"),
	z80Token(zJP,"pe,A"),
	z80Token(zEX,"de,hl"),
	z80Token(zCALL,"pe,A"),
	z80Token(zDB,"ed"),
	z80Token(zXOR,"B"),
	z80Token(zRST,"V"),
	z80Token(zRET,"p"),
	z80Token(zPOP,"af"),
	z80Token(zJP,"p,A"),
	z80Token(zDI,NULL),
	z80Token(zCALL,"p,A"),
	z80Token(zPUSH,"af"),
	z80Token(zOR,"B"),
	z80Token(zRST,"V"),
	z80Token(zRET,"m"),
	z80Token(zLD,"sp,hl"),
	z80Token(zJP,"m,A"),
	z80Token(zEI,NULL),
	z80Token(zCALL,"m,A"),
	z80Token(zDB,"fd"),
	z80Token(zCP,"B"),
	z80Token(zRST,"V")
    });
    return lookup.value(op);
}
